#ifndef EPD_SCREEN_TEST
#define EPD_SCREEN_TEST 0
#endif
#define EPD_WIDTH  200
#define EPD_HEIGHT 200
#define EPD_BITMAP_BYTES ((EPD_WIDTH * EPD_HEIGHT) / 8)

#if defined(EPD_TARGET_S3) || defined(CONFIG_IDF_TARGET_ESP32S3)

#define EPD_BLE_NAME "EPaper-S3"
#define EPD_DUAL_CORE_BLE 0
#define EPD_BLE_CORE 0
#define EPD_DISPLAY_CORE 1
#define EPD_CPU_MHZ 240
#define EPD_LIGHT_SLEEP_IDLE 0
#define EPD_SKIP_BOOT_EPD 1
#define EPD_BOOT_DELAY_MS 50

#define EPD_READY_GPIO 21

#else

#define EPD_BLE_NAME "EPaper-C3"
#define EPD_DUAL_CORE_BLE 0
#define EPD_CPU_MHZ 80
#define EPD_LIGHT_SLEEP_IDLE 0
#define EPD_SKIP_BOOT_EPD 1
#define EPD_BOOT_DELAY_MS 300
#define EPD_READY_GPIO (-1)

#endif

#define EPD_BLE_SVC "550e8400-e29b-41d4-a716-446655440001"
#define EPD_BLE_RX  "550e8400-e29b-41d4-a716-446655440002"
#define EPD_BLE_TX  "550e8400-e29b-41d4-a716-446655440003"
#define EPD_WIFI_AP_MODE 1
#define EPD_WIFI_SSID    "ESP32-EPaper"
#define EPD_WIFI_PASS    "12345678"

#define EPD_WIFI_STA_SSID ""
#define EPD_WIFI_STA_PASS ""

#define EPD_HTTP_PORT 80

#ifndef EPD_BLE_ENABLE
#define EPD_BLE_ENABLE 1
#endif

#define EPD_BLE_STANDALONE 1
#define EPD_BLE_DISCONNECT_COOLDOWN_MS 800
#define EPD_BLE_RAPID_DISC_BACKOFF_MAX_MS 30000
#define EPD_BLE_ADV_SUPPRESS_AFTER_RAPID 6
#define EPD_BLE_ADV_SUPPRESS_MS 15000
#define EPD_WIFI_OFF_WHEN_BLE 0
#define EPD_SLIDESHOW_PAUSE_BLE 1
#define EPD_AUTO_SLIDESHOW 0

#define EPD_BLE_ADV_OFF_WHEN_IDLE 0
#define EPD_BLE_ALWAYS_CONNECTABLE 1
#define EPD_BLE_CLEAR_BONDS_ON_BOOT 1
#define EPD_BLE_BOOT_AUTOCONNECT_MS 12000
#define EPD_BLE_GATT_IDLE_DISCONNECT_MS 25000
#define EPD_BLE_BOOT_DISCOVER_MS 600000
#define EPD_BLE_ADV_WATCHDOG_MS 5000
#define EPD_BLE_ADV_MIN_CONNECTABLE 0x20
#define EPD_BLE_ADV_MAX_CONNECTABLE 0x40
#define EPD_BLE_TX_LEVEL ESP_PWR_LVL_P9
#define EPD_BLE_UPLOAD_TIMEOUT_MS 120000
#define EPD_BLE_HOST_POLL_MS 333
#define EPD_BLE_RESTART_ADV_ON_CONNECT 0
#define EPD_BLE_CONNECT_GRACE_MS 8000

#define EPD_IDLE_LOOP_MS_CONNECTED 15
#define EPD_IDLE_LOOP_MS_PAIRING 60
#define EPD_IDLE_LOOP_MS_IDLE 400

#if EPD_SCREEN_TEST
#undef EPD_BLE_ENABLE
#define EPD_BLE_ENABLE 0
#undef EPD_LIGHT_SLEEP_IDLE
#define EPD_LIGHT_SLEEP_IDLE 0
#define EPD_SCREEN_TEST_INTERVAL_MS 3000
#endif
